"""add_api_key_to_users

Revision ID: c81546f00f10
Revises: 0bf43337a0a9
Create Date: 2025-11-04 03:58:55.722741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c81546f00f10"
down_revision = "0bf43337a0a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first if they don't exist
    from sqlalchemy import text
    
    # Create deliverymethod enum type
    op.execute(text("""
        DO $$ BEGIN
            CREATE TYPE deliverymethod AS ENUM ('IN_APP', 'EMAIL', 'WEBHOOK');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Create alerttype enum type
    op.execute(text("""
        DO $$ BEGIN
            CREATE TYPE alerttype AS ENUM ('SENTIMENT_SHIFT', 'RISK_INCREASE', 'THEME_CHANGE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Create reporttype enum type
    op.execute(text("""
        DO $$ BEGIN
            CREATE TYPE reporttype AS ENUM ('TEN_K', 'TEN_Q', 'EIGHT_K', 'ANNUAL', 'OTHER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Create fileformat enum type
    op.execute(text("""
        DO $$ BEGIN
            CREATE TYPE fileformat AS ENUM ('PDF', 'HTML', 'TXT', 'IXBRL');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Create downloadsource enum type
    op.execute(text("""
        DO $$ BEGIN
            CREATE TYPE downloadsource AS ENUM ('SEC_AUTO', 'MANUAL_UPLOAD');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Create processingstatus enum type
    op.execute(text("""
        DO $$ BEGIN
            CREATE TYPE processingstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Create shiftsignificance enum type
    op.execute(text("""
        DO $$ BEGIN
            CREATE TYPE shiftsignificance AS ENUM ('MINOR', 'MODERATE', 'MAJOR', 'CRITICAL');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Add columns with nullable=True first, then update with defaults, then set to NOT NULL
    op.add_column("alerts", sa.Column("delta_id", sa.UUID(), nullable=True))
    op.add_column(
        "alerts",
        sa.Column("actual_change_percentage", sa.Float(), nullable=True),
    )
    op.add_column(
        "alerts", sa.Column("alert_message", sa.Text(), nullable=True)
    )
    op.add_column("alerts", sa.Column("is_read", sa.Boolean(), nullable=True, server_default='false'))
    op.add_column(
        "alerts",
        sa.Column(
            "delivery_method",
            sa.Enum("IN_APP", "EMAIL", "WEBHOOK", name="deliverymethod", create_type=False),
            nullable=True,
            server_default=text("'IN_APP'::deliverymethod"),
        ),
    )
    op.add_column(
        "alerts", sa.Column("delivered_at", sa.DateTime(), nullable=True)
    )
    # Convert alert_type column from VARCHAR to enum using explicit cast
    op.execute(text("""
        ALTER TABLE alerts 
        ALTER COLUMN alert_type TYPE alerttype 
        USING alert_type::alerttype
    """))
    # Set default values for new columns before making them NOT NULL
    # Only update if there are existing alerts
    op.execute(text("""
        UPDATE alerts 
        SET delta_id = COALESCE(
            (SELECT id FROM narrative_deltas LIMIT 1),
            '00000000-0000-0000-0000-000000000000'::uuid
        )
        WHERE delta_id IS NULL
    """))
    op.execute(text("UPDATE alerts SET actual_change_percentage = 0.0 WHERE actual_change_percentage IS NULL"))
    op.execute(text("UPDATE alerts SET alert_message = 'Alert triggered' WHERE alert_message IS NULL"))
    
    # Now make columns NOT NULL
    op.alter_column("alerts", "delta_id", nullable=False)
    op.alter_column("alerts", "actual_change_percentage", nullable=False)
    op.alter_column("alerts", "alert_message", nullable=False)
    op.alter_column("alerts", "is_read", nullable=False)
    op.alter_column("alerts", "delivery_method", nullable=False)
    
    op.alter_column(
        "alerts",
        "threshold_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.drop_index("idx_alerts_active", table_name="alerts")
    op.drop_index("idx_alerts_company", table_name="alerts")
    op.drop_index("idx_alerts_user", table_name="alerts")
    op.create_index(
        op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_company_id"), "alerts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_delta_id"), "alerts", ["delta_id"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_is_read"), "alerts", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False
    )
    op.drop_constraint("alerts_company_id_fkey", "alerts", type_="foreignkey")
    op.drop_constraint("alerts_user_id_fkey", "alerts", type_="foreignkey")
    op.create_foreign_key(
        None, "alerts", "narrative_deltas", ["delta_id"], ["id"]
    )
    op.create_foreign_key(None, "alerts", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "alerts", "companies", ["company_id"], ["id"])
    op.drop_column("alerts", "is_active")
    op.drop_constraint(
        "companies_ticker_symbol_key", "companies", type_="unique"
    )
    op.drop_index("idx_companies_industry", table_name="companies")
    op.drop_index("idx_companies_sector", table_name="companies")
    op.drop_index("idx_companies_ticker", table_name="companies")
    op.drop_index("idx_companies_ticker_symbol", table_name="companies")
    op.create_index(
        op.f("ix_companies_industry"), "companies", ["industry"], unique=False
    )
    op.create_index(
        op.f("ix_companies_sector"), "companies", ["sector"], unique=False
    )
    op.create_index(
        op.f("ix_companies_ticker_symbol"),
        "companies",
        ["ticker_symbol"],
        unique=True,
    )
    # Convert financial_reports.report_type column to enum type
    op.execute(text("""
        ALTER TABLE financial_reports 
        ALTER COLUMN report_type TYPE reporttype 
        USING report_type::reporttype
    """))
    op.alter_column(
        "financial_reports",
        "fiscal_period",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.execute(text("""
        ALTER TABLE financial_reports 
        ALTER COLUMN file_format TYPE fileformat 
        USING file_format::fileformat
    """))
    op.execute(text("""
        ALTER TABLE financial_reports 
        ALTER COLUMN download_source TYPE downloadsource 
        USING download_source::downloadsource
    """))
    # Drop old default, convert type, then set new default
    op.execute(text("""
        ALTER TABLE financial_reports 
        ALTER COLUMN processing_status DROP DEFAULT
    """))
    op.execute(text("""
        ALTER TABLE financial_reports 
        ALTER COLUMN processing_status TYPE processingstatus 
        USING processing_status::processingstatus
    """))
    op.execute(text("""
        ALTER TABLE financial_reports 
        ALTER COLUMN processing_status SET DEFAULT 'PENDING'::processingstatus
    """))
    op.drop_index(
        "idx_financial_reports_company", table_name="financial_reports"
    )
    op.drop_index(
        "idx_financial_reports_company_filing_date",
        table_name="financial_reports",
    )
    op.drop_index(
        "idx_financial_reports_filing_date", table_name="financial_reports"
    )
    op.drop_index(
        "idx_financial_reports_status", table_name="financial_reports"
    )
    op.drop_index("idx_financial_reports_type", table_name="financial_reports")
    op.create_index(
        op.f("ix_financial_reports_company_id"),
        "financial_reports",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_reports_download_source"),
        "financial_reports",
        ["download_source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_reports_file_format"),
        "financial_reports",
        ["file_format"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_reports_filing_date"),
        "financial_reports",
        ["filing_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_reports_processing_status"),
        "financial_reports",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_reports_report_type"),
        "financial_reports",
        ["report_type"],
        unique=False,
    )
    op.drop_constraint(
        "financial_reports_company_id_fkey",
        "financial_reports",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "financial_reports", "companies", ["company_id"], ["id"]
    )
    op.alter_column(
        "narrative_analyses",
        "key_themes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "narrative_analyses",
        "risk_indicators",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "narrative_analyses",
        "narrative_sections",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "narrative_analyses",
        "financial_metrics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(
        "idx_narrative_analyses_created", table_name="narrative_analyses"
    )
    op.drop_index(
        "idx_narrative_analyses_report", table_name="narrative_analyses"
    )
    op.drop_index(
        "idx_narrative_analyses_report_id", table_name="narrative_analyses"
    )
    op.create_index(
        op.f("ix_narrative_analyses_report_id"),
        "narrative_analyses",
        ["report_id"],
        unique=False,
    )
    op.drop_constraint(
        "narrative_analyses_report_id_fkey",
        "narrative_analyses",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "narrative_analyses", "financial_reports", ["report_id"], ["id"]
    )
    # Convert shift_significance enum (handle both old and new enum names)
    op.execute(text("""
        DO $$ 
        BEGIN
            -- Drop old enum type if it exists and has different name
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'shift_significance_enum') THEN
                ALTER TABLE narrative_deltas ALTER COLUMN shift_significance TYPE shiftsignificance 
                USING shift_significance::text::shiftsignificance;
            ELSE
                ALTER TABLE narrative_deltas ALTER COLUMN shift_significance TYPE shiftsignificance 
                USING shift_significance::shiftsignificance;
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                -- If already correct type, just continue
                NULL;
        END $$;
    """))
    op.drop_index("idx_narrative_deltas_base", table_name="narrative_deltas")
    op.drop_index(
        "idx_narrative_deltas_company_created", table_name="narrative_deltas"
    )
    op.drop_index(
        "idx_narrative_deltas_company_id", table_name="narrative_deltas"
    )
    op.drop_index(
        "idx_narrative_deltas_comparison", table_name="narrative_deltas"
    )
    op.drop_index(
        "idx_narrative_deltas_shift_significance",
        table_name="narrative_deltas",
    )
    op.create_index(
        op.f("ix_narrative_deltas_base_analysis_id"),
        "narrative_deltas",
        ["base_analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_narrative_deltas_company_id"),
        "narrative_deltas",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_narrative_deltas_comparison_analysis_id"),
        "narrative_deltas",
        ["comparison_analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_narrative_deltas_shift_significance"),
        "narrative_deltas",
        ["shift_significance"],
        unique=False,
    )
    op.drop_constraint(
        "narrative_deltas_comparison_analysis_id_fkey",
        "narrative_deltas",
        type_="foreignkey",
    )
    op.drop_constraint(
        "narrative_deltas_base_analysis_id_fkey",
        "narrative_deltas",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_narrative_deltas_company_id",
        "narrative_deltas",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "narrative_deltas",
        "narrative_analyses",
        ["base_analysis_id"],
        ["id"],
    )
    op.create_foreign_key(
        None, "narrative_deltas", "companies", ["company_id"], ["id"]
    )
    op.create_foreign_key(
        None,
        "narrative_deltas",
        "narrative_analyses",
        ["comparison_analysis_id"],
        ["id"],
    )
    op.drop_column("narrative_deltas", "significant_changes")
    op.drop_column("narrative_deltas", "delta_summary")
    op.drop_index(
        "idx_narrative_embeddings_analysis_section",
        table_name="narrative_embeddings",
    )
    op.drop_constraint(
        "narrative_embeddings_analysis_id_fkey",
        "narrative_embeddings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "narrative_embeddings",
        "narrative_analyses",
        ["analysis_id"],
        ["id"],
    )
    op.add_column(
        "users", sa.Column("api_key_hash", sa.String(length=64), nullable=True)
    )
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_users_subscription_tier", table_name="users")
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_index(
        op.f("ix_users_api_key_hash"), "users", ["api_key_hash"], unique=True
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_subscription_tier"),
        "users",
        ["subscription_tier"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_subscription_tier"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_api_key_hash"), table_name="users")
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.create_index(
        "idx_users_subscription_tier",
        "users",
        ["subscription_tier"],
        unique=False,
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.drop_column("users", "api_key_hash")
    op.drop_constraint(None, "narrative_embeddings", type_="foreignkey")
    op.create_foreign_key(
        "narrative_embeddings_analysis_id_fkey",
        "narrative_embeddings",
        "narrative_analyses",
        ["analysis_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "idx_narrative_embeddings_analysis_section",
        "narrative_embeddings",
        ["analysis_id", "section_type"],
        unique=False,
    )
    op.add_column(
        "narrative_deltas",
        sa.Column(
            "delta_summary", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "narrative_deltas",
        sa.Column(
            "significant_changes",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "narrative_deltas", type_="foreignkey")
    op.drop_constraint(None, "narrative_deltas", type_="foreignkey")
    op.drop_constraint(None, "narrative_deltas", type_="foreignkey")
    op.create_foreign_key(
        "fk_narrative_deltas_company_id",
        "narrative_deltas",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "narrative_deltas_base_analysis_id_fkey",
        "narrative_deltas",
        "narrative_analyses",
        ["base_analysis_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "narrative_deltas_comparison_analysis_id_fkey",
        "narrative_deltas",
        "narrative_analyses",
        ["comparison_analysis_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_narrative_deltas_shift_significance"),
        table_name="narrative_deltas",
    )
    op.drop_index(
        op.f("ix_narrative_deltas_comparison_analysis_id"),
        table_name="narrative_deltas",
    )
    op.drop_index(
        op.f("ix_narrative_deltas_company_id"), table_name="narrative_deltas"
    )
    op.drop_index(
        op.f("ix_narrative_deltas_base_analysis_id"),
        table_name="narrative_deltas",
    )
    op.create_index(
        "idx_narrative_deltas_shift_significance",
        "narrative_deltas",
        ["shift_significance"],
        unique=False,
    )
    op.create_index(
        "idx_narrative_deltas_comparison",
        "narrative_deltas",
        ["comparison_analysis_id"],
        unique=False,
    )
    op.create_index(
        "idx_narrative_deltas_company_id",
        "narrative_deltas",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "idx_narrative_deltas_company_created",
        "narrative_deltas",
        ["company_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_narrative_deltas_base",
        "narrative_deltas",
        ["base_analysis_id"],
        unique=False,
    )
    op.alter_column(
        "narrative_deltas",
        "shift_significance",
        existing_type=sa.Enum(
            "MINOR", "MODERATE", "MAJOR", "CRITICAL", name="shiftsignificance"
        ),
        type_=postgresql.ENUM(
            "MINOR",
            "MODERATE",
            "MAJOR",
            "CRITICAL",
            name="shift_significance_enum",
        ),
        existing_nullable=False,
    )
    op.drop_constraint(None, "narrative_analyses", type_="foreignkey")
    op.create_foreign_key(
        "narrative_analyses_report_id_fkey",
        "narrative_analyses",
        "financial_reports",
        ["report_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_narrative_analyses_report_id"),
        table_name="narrative_analyses",
    )
    op.create_index(
        "idx_narrative_analyses_report_id",
        "narrative_analyses",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        "idx_narrative_analyses_report",
        "narrative_analyses",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        "idx_narrative_analyses_created",
        "narrative_analyses",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "narrative_analyses",
        "financial_metrics",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "narrative_analyses",
        "narrative_sections",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "narrative_analyses",
        "risk_indicators",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "narrative_analyses",
        "key_themes",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_constraint(None, "financial_reports", type_="foreignkey")
    op.create_foreign_key(
        "financial_reports_company_id_fkey",
        "financial_reports",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_financial_reports_report_type"),
        table_name="financial_reports",
    )
    op.drop_index(
        op.f("ix_financial_reports_processing_status"),
        table_name="financial_reports",
    )
    op.drop_index(
        op.f("ix_financial_reports_filing_date"),
        table_name="financial_reports",
    )
    op.drop_index(
        op.f("ix_financial_reports_file_format"),
        table_name="financial_reports",
    )
    op.drop_index(
        op.f("ix_financial_reports_download_source"),
        table_name="financial_reports",
    )
    op.drop_index(
        op.f("ix_financial_reports_company_id"), table_name="financial_reports"
    )
    op.create_index(
        "idx_financial_reports_type",
        "financial_reports",
        ["report_type"],
        unique=False,
    )
    op.create_index(
        "idx_financial_reports_status",
        "financial_reports",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        "idx_financial_reports_filing_date",
        "financial_reports",
        ["filing_date"],
        unique=False,
    )
    op.create_index(
        "idx_financial_reports_company_filing_date",
        "financial_reports",
        ["company_id", sa.text("filing_date DESC")],
        unique=False,
    )
    op.create_index(
        "idx_financial_reports_company",
        "financial_reports",
        ["company_id"],
        unique=False,
    )
    op.alter_column(
        "financial_reports",
        "processing_status",
        existing_type=sa.Enum(
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "FAILED",
            name="processingstatus",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.alter_column(
        "financial_reports",
        "download_source",
        existing_type=sa.Enum(
            "SEC_AUTO", "MANUAL_UPLOAD", name="downloadsource"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "financial_reports",
        "file_format",
        existing_type=sa.Enum(
            "PDF", "HTML", "TXT", "IXBRL", name="fileformat"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "financial_reports",
        "fiscal_period",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "financial_reports",
        "report_type",
        existing_type=sa.Enum(
            "TEN_K", "TEN_Q", "EIGHT_K", "ANNUAL", "OTHER", name="reporttype"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_companies_ticker_symbol"), table_name="companies")
    op.drop_index(op.f("ix_companies_sector"), table_name="companies")
    op.drop_index(op.f("ix_companies_industry"), table_name="companies")
    op.create_index(
        "idx_companies_ticker_symbol",
        "companies",
        ["ticker_symbol"],
        unique=False,
    )
    op.create_index(
        "idx_companies_ticker", "companies", ["ticker_symbol"], unique=False
    )
    op.create_index(
        "idx_companies_sector", "companies", ["sector"], unique=False
    )
    op.create_index(
        "idx_companies_industry", "companies", ["industry"], unique=False
    )
    op.create_unique_constraint(
        "companies_ticker_symbol_key", "companies", ["ticker_symbol"]
    )
    op.add_column(
        "alerts",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "alerts", type_="foreignkey")
    op.drop_constraint(None, "alerts", type_="foreignkey")
    op.drop_constraint(None, "alerts", type_="foreignkey")
    op.create_foreign_key(
        "alerts_user_id_fkey",
        "alerts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "alerts_company_id_fkey",
        "alerts",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_is_read"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_delta_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_company_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.create_index("idx_alerts_user", "alerts", ["user_id"], unique=False)
    op.create_index(
        "idx_alerts_company", "alerts", ["company_id"], unique=False
    )
    op.create_index("idx_alerts_active", "alerts", ["is_active"], unique=False)
    op.alter_column(
        "alerts",
        "threshold_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "alerts",
        "alert_type",
        existing_type=sa.Enum(
            "SENTIMENT_SHIFT",
            "RISK_INCREASE",
            "THEME_CHANGE",
            name="alerttype",
        ),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_column("alerts", "delivered_at")
    op.drop_column("alerts", "delivery_method")
    op.drop_column("alerts", "is_read")
    op.drop_column("alerts", "alert_message")
    op.drop_column("alerts", "actual_change_percentage")
    op.drop_column("alerts", "delta_id")
    # ### end Alembic commands ###
